### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gpelatis** [s77rt/hashcat.launcher#1]
Hi , ty for your work on this tool .
I have been trying to use it but everytime i get "Error: The specified parameter cannot use '1.2' as a value - must be a number"
When i change the format to hash[:salt:]:plain:hex_plain the i get the same error but with '1.2.3'
Sorry if this is not the place to post this.

**Comment by s77rt** [comment]
Hi,
You are just using an unsupported version of hashcat (i guess v5.1.0)
hashcat min version is v5.1.0+1774
you can get the beta version from: [https://hashcat.net/beta/](https://hashcat.net/beta/)

**Comment by gpelatis** [comment]
ty :D

**Comment by s77rt** [comment]
you are welcome :)
