### ISSUE TITLE
Hashcat doesn't have correct Progress Screen

### ISSUE THREAD

**Issue by alex2101998** [s77rt/hashcat.launcher#101]
On Windows i was trying your new hashcat launcher. When i started a Task i was a bit disappointed by that Progress Screen because its so empty. I looked into your Preview gif and realized it doesn't look alike. This must be a bug right?

Here is an example Image
![image](https://user-images.githubusercontent.com/24660968/189317400-1455efb7-d63d-4633-a367-775e4a0b9c33.png)

**Comment by s77rt** [comment]
Hi Alex,
Yeah something seems wrong. Probably in the JSON parser.
Can you paste the messages you got in the right? (under Terminal)

**Comment by alex2101998** [comment]
Sure, it looks like this

`{ "session": "Task #1", "guess": { "guess_base": "C:\Users\user\Desktop\hashcat.launcher_1.1.3_windows\hashcat\dictionaries\Top32Million-2017-08.txt", "guess_base_count": 1, "guess_base_offset": 1, "guess_base_percent": 100.00, "guess_mask_length": 4294967295, "guess_mod": null, "guess_mod_count": 1, "guess_mod_offset": 1, "guess_mod_percent": 100.00, "guess_mode": 1 }, "status": 3, "target": "$ml$54644$942295ec22615b664a3e38f53264f693b269a9d04...ca7d60", "progress": [0, 32496543], "restore_point": 0, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "device_name": "Intel(R) UHD Graphics", "device_type": "GPU", "speed": 72, "util": -1 } ], "time_start": 1662723179, "estimated_stop": 1663171584 }
{ "session": "Task #1", "guess": { "guess_base": "C:\Users\user\Desktop\hashcat.launcher_1.1.3_windows\hashcat\dictionaries\Top32Million-2017-08.txt", "guess_base_count": 1, "guess_base_offset": 1, "guess_base_percent": 100.00, "guess_mask_length": 4294967295, "guess_mod": null, "guess_mod_count": 1, "guess_mod_offset": 1, "guess_mod_percent": 100.00, "guess_mode": 1 }, "status": 3, "target": "$ml$54644$942295ec22615b664a3e38f53264f693b269a9d04...ca7d60", "progress": [0, 32496543], "restore_point": 0, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "device_name": "Intel(R) UHD Graphics", "device_type": "GPU", "speed": 72, "util": -1 } ], "time_start": 1662723179, "estimated_stop": 1663173312 }
{ "session": "Task #1", "guess": { "guess_base": "C:\Users\user\Desktop\hashcat.launcher_1.1.3_windows\hashcat\dictionaries\Top32Million-2017-08.txt", "guess_base_count": 1, "guess_base_offset": 1, "guess_base_percent": 100.00, "guess_mask_length": 4294967295, "guess_mod": null, "guess_mod_count": 1, "guess_mod_offset": 1, "guess_mod_percent": 100.00, "guess_mode": 1 }, "status": 3, "target": "$ml$54644$942295ec22615b664a3e38f53264f693b269a9d04...ca7d60", "progress": [0, 32496543], "restore_point": 0, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "device_name": "Intel(R) UHD Graphics", "device_type": "GPU", "speed": 73, "util": -1 } ], "time_start": 1662723179, "estimated_stop": 1663167672 }
{ "session": "Task #1", "guess": { "guess_base": "C:\Users\user\Desktop\hashcat.launcher_1.1.3_windows\hashcat\dictionaries\Top32Million-2017-08.txt", "guess_base_count": 1, "guess_base_offset": 1, "guess_base_percent": 100.00, "guess_mask_length": 4294967295, "guess_mod": null, "guess_mod_count": 1, "guess_mod_offset": 1, "guess_mod_percent": 100.00, "guess_mode": 1 }, "status": 3, "target": "$ml$54644$942295ec22615b664a3e38f53264f693b269a9d04...ca7d60", "progress": [0, 32496543], "restore_point": 0, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "device_name": "Intel(R) UHD Graphics", "device_type": "GPU", "speed": 72, "util": -1 } ], "time_start": 1662723179, "estimated_stop": 1663173716 }
{ "session": "Task #1", "guess": { "guess_base": "C:\Users\user\Desktop\hashcat.launcher_1.1.3_windows\hashcat\dictionaries\Top32Million-2017-08.txt", "guess_base_count": 1, "guess_base_offset": 1, "guess_base_percent": 100.00, "guess_mask_length": 4294967295, "guess_mod": null, "guess_mod_count": 1, "guess_mod_offset": 1, "guess_mod_percent": 100.00, "guess_mode": 1 }, "status": 3, "target": "$ml$54644$942295ec22615b664a3e38f53264f693b269a9d04...ca7d60", "progress": [0, 32496543], "restore_point": 0, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "device_name": "Intel(R) UHD Graphics", "device_type": "GPU", "speed": 72, "util": -1 } ], "time_start": 1662723179, "estimated_stop": 1663170772 }
{ "session": "Task #1", "guess": { "guess_base": "C:\Users\user\Desktop\hashcat.launcher_1.1.3_windows\hashcat\dictionaries\Top32Million-2017-08.txt", "guess_base_count": 1, "guess_base_offset": 1, "guess_base_percent": 100.00, "guess_mask_length": 4294967295, "guess_mod": null, "guess_mod_count": 1, "guess_mod_offset": 1, "guess_mod_percent": 100.00, "guess_mode": 1 }, "status": 3, "target": "$ml$54644$942295ec22615b664a3e38f53264f693b269a9d04...ca7d60", "progress": [0, 32496543], "restore_point": 0, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "device_name": "Intel(R) UHD Graphics", "device_type": "GPU", "speed": 72, "util": -1 } ], "time_start": 1662723179, "estimated_stop": 1663171407 }`

**Comment by s77rt** [comment]
Thanks for sharing, this looks to be a hashcat bug (see https://github.com/hashcat/hashcat/issues/3453)
For now you can use hashcat v6.2.5 (just replace the hashcat folder)

**Comment by alex2101998** [comment]
Ah, i see. Thank you so far :)

**Comment by s77rt** [comment]
Since the issue has been fixed, you can now use a beta version of hashcat https://hashcat.net/beta/ to get the v6.2.6 features and the bug fix.

**Comment by s77rt** [comment]
Please try with the latest version (v1.1.4)
Should be fixed now

**Comment by Burtdoe** [comment]
Same problem here with launcher 1.1.5   Hashcat 6.2.6

![Screenshot 2024-03-11 210347](https://github.com/s77rt/hashcat.launcher/assets/45123776/21cf42bc-b95b-43a4-92b2-973037a80c5b)

**Comment by s77rt** [comment]
@Burtdoe Are you using the built-in hashcat? or another version?

**Comment by Burtdoe** [comment]
That one:   
https://hashcat.net/hashcat/
-->  hashcat binaries | v6.2.6 | 2022.09.02

**Comment by s77rt** [comment]
Please use the version that's shipped with hashcat.launcher

**Comment by Burtdoe** [comment]
Ok, got it
I didn´t know there is a difference...

Thanks
