### ISSUE TITLE
Total running time of each Task

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#102]
It would be nice to see how long time each Tasks takes. Right now you can see from start time of a dictionary, mask and such. Not how many x days , hours and such running time of the Task.

**Comment by s77rt** [comment]
i think this is by design how hashcat works
it may be best to make a [feature request](https://github.com/hashcat/hashcat/issues/new?labels=new+feature&template=feature_request_-_other.md) for such functionality then it can be ported to hashcat.launcher

**Comment by foordeluxe** [comment]
Is this not possible to programming without hashcat help? I mean a timer or something that showing how long the task has been running?

**Comment by s77rt** [comment]
not really that easy, a timer will have to be maintained for for every (pause, resume, etc...)
also the bigger problem is how to track tasks after closing hashcat.launcher


at this point this is not possible, soon there will be a version 2 that handles things completely different and i think then we will be able to add our own functionalities without relying on hashcat itself, but this may come at a cost...

**Comment by foordeluxe** [comment]
Interesting in not relying on hashcat. But for me this is fine as it is now.
