### ISSUE TITLE
Newest version can't find hashcat

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#105]
I have tried to use hashcat.launcher but I get that hashcat is not found. I know it's added inside the 7z archive. So I tried to put hashcat.launcher inside the hashcat folder. But still getting that error.

I use Ubuntu.

**Comment by foordeluxe** [comment]
I needed to compile hashcat self. Now it works.

**Comment by s77rt** [comment]
I can't replicate the issue
You don't have to recompile anything. Just extract the archive and run hashcat.launcher
