### ISSUE TITLE
MacOS binaries contain Windows binaries 

### ISSUE THREAD

**Issue by ShadowRoi** [s77rt/hashcat.launcher#106]
The macOS pre compiled binaries contain Windows binaries... It contains exe files. Anyways other than that really cool project congrats

**Comment by s77rt** [comment]
Hi,
What exe files you are referring to?
hashcat itself may contain exe files (that's what hashcat binaries comes with). but hashcat.launcher is shipped with only the os target executable

**Comment by s77rt** [comment]
Closing for now.
