### ISSUE TITLE
Part of the Gui is blank 

### ISSUE THREAD

**Issue by GameDevKitY** [s77rt/hashcat.launcher#108]
![Capture](https://user-images.githubusercontent.com/97373169/202578859-bba78396-24e5-4ff0-af6f-451917c24ed5.PNG)
I tried reinstalling it too, nothing fixes it, it was working the first time I ran it but not anymore

**Comment by s77rt** [comment]
Hi,
What version of hashcat.launcher you are running? Can you try with the latest version?

**Comment by GameDevKitY** [comment]
> Hi, What version of hashcat.launcher you are running? Can you try with the latest version?

Im using v1.1.4 which is the latest version

**Comment by s77rt** [comment]
did you change the hashcat version? If possible attach the .restore file related to that task

**Comment by GameDevKitY** [comment]
> did you change the hashcat version? If possible attach the .restore file related to that task

for some reason using the hash version that comes with the launcher works while the newest hashcat version doesnt work

**Comment by s77rt** [comment]
Yeah that's a bug in hashcat, similar issue has been opened about this already https://github.com/s77rt/hashcat.launcher/issues/101

**Comment by s77rt** [comment]
Closing for now
