### ISSUE TITLE
Add ability to use 3rd wordlist in Combinator

### ISSUE THREAD

**Issue by seeker7r4c3r** [s77rt/hashcat.launcher#110]
I would like to use a specific format for a combinator attack.  {adjective}{noun}{###}. I only see the option for 2 in the launcher. Or maybe add a section for custom args to be added.

**Comment by s77rt** [comment]
You can add custom arguments but they are applied globally to every new task.

I'm not sure what exactly you are trying to achieve but if it's supposed by hashcat and I just missed adding such an option then this can be fixed

**Comment by seeker7r4c3r** [comment]
I want to use 3 dictionaries in a combinator. Currently i only see the
option to use 2.

**Comment by s77rt** [comment]
Is this option available in hashcat? If so please provide an example (command lineà

**Comment by seeker7r4c3r** [comment]
It appears to be.

Heres the link to what Im trying to do.

https://github.com/LivingInSyn/netgear_hashcat_wordlist

**Comment by s77rt** [comment]
This is using pipe to supply one wordlist to hashcat
That wordlist happen to be the combination of three other wordlists using combinator3 tool

hashcat.launcher does not support pipe, what you can do is combine the three wordlists and use dictionary mode in hashcat.launcher
