### ISSUE TITLE
GPU not working

### ISSUE THREAD

**Issue by jcpamart** [s77rt/hashcat.launcher#113]
Hi
I have make a task with GPU selected.
But it seems not be used.
Cuda is installed.

Thanks for your help

**Comment by s77rt** [comment]
Hi @jcpamart 
Mind sharing what went wrong and how you managed to solve it so others can benefit from this too

**Comment by jcpamart** [comment]
Sorry,

I thought I can solved it by myself, but not.
I retry it, but with the same issue.
My 1080Ti is not using to this attack...
![image](https://user-images.githubusercontent.com/81438089/220209363-3f49fadc-736c-413e-8f07-0682de2bc200.png)

**Comment by jcpamart** [comment]
![image](https://user-images.githubusercontent.com/81438089/220209499-7974f4f4-1c01-41d1-9dc3-f3a82cd53996.png)

**Comment by s77rt** [comment]
Can you run the benchmark?

**Comment by jcpamart** [comment]
> Can you run the benchmark?

Could you tell me where it is ?

**Comment by s77rt** [comment]
Check the options while trying to create a new task

**Comment by s77rt** [comment]
Yes, I think the button is "Reference"

**Comment by jcpamart** [comment]
With an easy file rar encrypted, I have this on the terminal

Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 1 (Rar!): Separator unmatched
No hashes loaded.
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 2 (�L�3...~��D*X�2�r���qB��Z�������{�>�): Separator unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 3 (�	��l�...��|c��C"x�na9���[V���ae �$[D\): Separator unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 4 (�M): Separator unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 5 (`4�����tA��@�α7���v�diy�[������): Separator unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 6 (x�ޚ�5���Em)f���f): Signature unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 7 (\y���...m����Ք�@۱�:D4s䌩�e��4k�XU�U): Separator unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 8 (�4�R�����fOo��): Separator unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 9 (_I��/r...�������<�'��5�4���c�h����!3v�R): Separator unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 10 (^G�...	���"����	��\G�0;ڕ�<炸]U`v�): Separator unmatched
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.rar' on line 11 (�/ (�C...��l�$?�����*p&U7N�,�Vy�=�f�V): Separator unmatched

**Comment by s77rt** [comment]
Okay so hashcat is working fine.
You are entering the wrong hash file, you should not use the .rar file directly. You have to extract the hashes using rar2john or similar tools, and then use that hash.

**Comment by jcpamart** [comment]
Ah OK, I'll try it

**Comment by jcpamart** [comment]
OK, Think i progress ! LOL !

![image](https://user-images.githubusercontent.com/81438089/220358188-8e0ad8c2-d1b9-4e2e-92ca-d495ce0ff1ab.png)
I save it in a txt format.
Maybe a wrong idea ?

And the terminal answer me : 
Hashfile 'C:\Temp\Hashcat Launcher\hashcat\hashes\2.txt' on line 1 (2.rar:...7c95bbb48f8d4$8$e0a6632e44c53ce1): Signature unmatched
No hashes loaded.

**Comment by jcpamart** [comment]
Done !

I change the .txt to .hash, and delete the beginning of the file (it's name) 2.rar, and begin the line by : $rar

Thank you very much for your help

**Comment by s77rt** [comment]
Glad this is fixed now.
Closing.
