### ISSUE TITLE
127.0.0.1 > 0.0.0.0

### ISSUE THREAD

**Issue by fuad00** [s77rt/hashcat.launcher#115]
How can i run webui on 0.0.0.0 and o exact port?

**Comment by s77rt** [comment]
This is not a feature that is exported to users. However if you are willing to fork the repo you can modify that [here](https://github.com/s77rt/hashcat.launcher/blob/510a66cc76d5f53a6a81731dedd2e397798e606c/server.go#L13).

But please keep in mind that hashcat.launcher is not a web app. The web is only used to host the UI. Accessing the UI from outside hashcat.launcher is useless.
