### ISSUE TITLE
Using --session x --restore doesn't work

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#12]
I use this as advanced settings, --session session_name. But then later when I want to use that session and restore the progress it start the program then later stops. I don't know why.

I use Windows 10 Pro x64 - 20H2 (19042.630)

**Comment by foordeluxe** [comment]
The log file can be found here: https://pastebin.com/GcGzxkMG

**Comment by s77rt** [comment]
> The --restore command does not need nor allow any further arguments except from --session (and --restore itself).   
> - https://hashcat.net/wiki/doku.php?id=restore

the bug is when you specify --restore in the extra args, hashcat.launcher is supposed to ignore all the other arguments but it's not thus hashcat exit.

Thanks for the report this will be fixed...

**Comment by s77rt** [comment]
Fixed on v0.4.0
