### ISSUE TITLE
Set browser to use for GUI?

### ISSUE THREAD

**Issue by JoMaZu787** [s77rt/hashcat.launcher#120]
Is it possible to change the browser used by hashcat.launcher to display its UI? On my computer (running Windows 11) it will always use Microsoft Edge, which, for obvious reasons, i do not want to use. I have Brave Browser installed, which is based on Chromium, and it is set as the default browser.

**Comment by s77rt** [comment]
Hmm, there is no explicit way but there may be a workaround. hashcat.launcher uses [lorca](https://github.com/zserge/lorca) for the gui and those are the paths that are being checked in order:

```go
                paths = []string{
                        os.Getenv("LocalAppData") + "/Google/Chrome/Application/chrome.exe",
                        os.Getenv("ProgramFiles") + "/Google/Chrome/Application/chrome.exe",
                        os.Getenv("ProgramFiles(x86)") + "/Google/Chrome/Application/chrome.exe",
                        os.Getenv("LocalAppData") + "/Chromium/Application/chrome.exe",
                        os.Getenv("ProgramFiles") + "/Chromium/Application/chrome.exe",
                        os.Getenv("ProgramFiles(x86)") + "/Chromium/Application/chrome.exe",
                        os.Getenv("ProgramFiles(x86)") + "/Microsoft/Edge/Application/msedge.exe",
                        os.Getenv("ProgramFiles") + "/Microsoft/Edge/Application/msedge.exe",
                }
```

I think you can use Brave browser if you map one of the chrome or chromium folders to Brave. You may be able to do that using `mklink`.

**Comment by JoMaZu787** [comment]
I tried, but it did not seem to work. I am currently trying to make the code do what i want using x64dbg

**Comment by s77rt** [comment]
Another option is to fork both hashcat.launcher and lorca and update the files paths as per your need.

Or simply just install chromium. I don't see how Brave would offer any UX diff for hashcat.launcher

**Comment by JoMaZu787** [comment]
> Or simply just install chromium. I don't see how Brave would offer any UX diff for hashcat.launcher
Yeah I'm probably just going to do that.
