### ISSUE TITLE
select algorithm

### ISSUE THREAD

**Issue by pdb613** [s77rt/hashcat.launcher#126]
Hello my english is not so good i try to explain i used  hashcat launcher but don't know what the mean with select algorithm.

 what most i type and were can  found algorithm i hope someone can explain for me kind Regards Per

**Comment by s77rt** [comment]
I'm not sure how.I can make this clearer. Algorithm is self-explanatory. What are you trying to use hashcat.launcher for exactly?

**Comment by pdb613** [comment]
Thank for your reaction I try to see my forgotten password from my veracrypt container I know some letters I try hash cat but don’t know the code I need kind regards per de bruijn

Verstuurd vanaf mijn iPhone

Op 26 dec. 2023 om 17:52 heeft Abdelhafidh Belalia ***@***.***> het volgende geschreven:

﻿

I'm not sure how.I can make this clearer. Algorithm is self-explanatory. What are you trying to use hashcat.launcher for exactly?

**Comment by s77rt** [comment]
In this case in the algorithm list you should select veracrypt. There is a quite a variation see examples here https://hashcat.net/wiki/doku.php?id=example_hashes. Since this is not hashcat.launcher specific I think it would be better to ask on hashcat forum.
