### ISSUE TITLE
A way to bypass current wordlist to next one while dictionary attacking

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#13]
In hashcat you can bypass a current wordlist when in dictionary attack mode. And force to a new one.
Right now you can only pause or stop current dictionary attack that is going on. And not bypass it and move to the next wordlist.
Is this possible to get this added to this tool?

**Comment by s77rt** [comment]
Noted, will be added

**Comment by s77rt** [comment]
Added on v0.4.0
