### ISSUE TITLE
GUI crashes when choosing hashcat binary

### ISSUE THREAD

**Issue by Jaja51** [s77rt/hashcat.launcher#14]
Hello,

The GUI crashes when I select the path to hashcat's binary:

`go run main.go
Welcome to hashcat.launcher v0.3.0
can't execute subprocess: fork/exec /home/jean/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher/hashcat.bin: no such file or directory
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f4563f31e40]

runtime stack:
runtime.throw(0xd9f0bb, 0x2a)
        /usr/lib64/go/1.12/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /usr/lib64/go/1.12/src/runtime/signal_unix.go:374 +0x4a9

goroutine 36 [syscall]:
runtime.cgocall(0xb73220, 0xc000067bf8, 0x7f45040023a0)
        /usr/lib64/go/1.12/src/runtime/cgocall.go:128 +0x5b fp=0xc000067bc8 sp=0xc000067b90 pc=0x4a227b
github.com/gotk3/gotk3/gtk._Cfunc_gtk_dialog_run(0x7f45040023a0, 0x7f4500000000)
        _cgo_gotypes.go:8410 +0x49 fp=0xc000067bf8 sp=0xc000067bc8 pc=0x93e3d9
github.com/gotk3/gotk3/gtk.(*Dialog).Run.func1(0xc000523020, 0xc000010601)
        /home/jean/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:2963 +0x64 fp=0xc000067c38 sp=0xc000067bf8 pc=0x9d82e4
github.com/gotk3/gotk3/gtk.(*Dialog).Run(0xc000523020, 0xc000010601)
        /home/jean/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:2963 +0x2b fp=0xc000067c58 sp=0xc000067c38 pc=0x98f59b
github.com/sqweek/dialog.chooseFile(0xd85972, 0x9, 0xd81363, 0x4, 0x0, 0xc000067e58, 0x0, 0x0, 0x0, 0x0)
        /home/jean/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200601143742-43ea34326190/dlgs_linux.go:79 +0x36c fp=0xc000067db8 sp=0xc000067c58 pc=0xb1432c
github.com/sqweek/dialog.(*FileBuilder).load(...)
        /home/jean/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200601143742-43ea34326190/dlgs_linux.go:45
github.com/sqweek/dialog.(*FileBuilder).Load(...)
        /home/jean/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200601143742-43ea34326190/dlgs.go:112
github.com/s77rt/hashcat%2elauncher.optionsScreen.func1(0xd857ef, 0x9)
        /home/jean/Downloads/hashcat.launcher-0.3.0/optionsScreen.go:12 +0x228 fp=0xc000067ea0 sp=0xc000067db8 pc=0xb52718
fyne.io/fyne/widget.(*Select).updateSelected(0xc0003b8000, 0xd857ef, 0x9)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/select.go:246 +0x6a fp=0xc000067ec0 sp=0xc000067ea0 pc=0x8412ca
fyne.io/fyne/widget.(*Select).SetSelected(0xc0003b8000, 0xd857ef, 0x9)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/select.go:237 +0xc6 fp=0xc000067f08 sp=0xc000067ec0 pc=0x841236
fyne.io/fyne/widget.(*Select).optionTapped(...)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/select.go:147
fyne.io/fyne/widget.(*Select).Tapped.func2()
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/select.go:166 +0x42 fp=0xc000067f38 sp=0xc000067f08 pc=0x847cf2
fyne.io/fyne/widget.(*menuItem).Tapped(0xc00018a070, 0xc000024600)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/menu_item.go:135 +0x8d fp=0xc000067f58 sp=0xc000067f38 pc=0x83acfd
fyne.io/fyne/internal/driver/glfw.(*window).mouseClicked.func6()
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/window.go:695 +0x66 fp=0xc000067f98 sp=0xc000067f58 pc=0x86ba76
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc00037c000)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/window.go:1102 +0x7a fp=0xc000067fd8 sp=0xc000067f98 pc=0x86949a
runtime.goexit()
        /usr/lib64/go/1.12/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000067fe0 sp=0xc000067fd8 pc=0x4f7e01
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/window.go:1126 +0x103

goroutine 1 [select, locked to thread]:
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc0000bc410)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/loop.go:90 +0x197
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc0000bc410)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/driver.go:71 +0x37
main.main()
        /home/jean/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher/main.go:26 +0x1bb

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib64/go/1.12/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib64/go/1.12/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib64/go/1.12/src/os/signal/signal_unix.go:29 +0x41

goroutine 20 [sleep]:
runtime.goparkunlock(...)
        /usr/lib64/go/1.12/src/runtime/proc.go:307
time.Sleep(0x22ecb25c00)
        /usr/lib64/go/1.12/src/runtime/time.go:105 +0x159
fyne.io/fyne/internal/painter.svgCacheJanitor.func1()
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/painter/svg_cache.go:51 +0x116
sync.(*Once).Do(0x1d4e1c0, 0xc0000ac2e0)
        /usr/lib64/go/1.12/src/sync/once.go:44 +0xb3
created by fyne.io/fyne/internal/painter.svgCacheJanitor
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/painter/svg_cache.go:49 +0x9b

goroutine 21 [chan receive]:
fyne.io/fyne/app.newAppWithDriver.func1(0xc0000962a0, 0xc0000b0720)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/app/app.go:113 +0x3d
created by fyne.io/fyne/app.newAppWithDriver
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/app/app.go:111 +0x184

goroutine 22 [syscall]:
syscall.Syscall6(0xe8, 0xe, 0xc000209d14, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.12/src/syscall/asm_linux_amd64.s:44 +0x5
golang.org/x/sys/unix.EpollWait(0xe, 0xc000209d14, 0x7, 0x7, 0xffffffffffffffff, 0xc000209d10, 0x0, 0xc00008ac00)
        /home/jean/go/pkg/mod/golang.org/x/sys@v0.0.0-20200327173247-9dae0f8f5775/unix/zsyscall_linux_amd64.go:76 +0x72
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc0000c4cc0, 0xdac200, 0xc0000c4cc0, 0x0)
        /home/jean/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify_poller.go:86 +0x91
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0000bc460)
        /home/jean/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify.go:192 +0x18a
created by github.com/fsnotify/fsnotify.NewWatcher
        /home/jean/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify.go:59 +0x1a8

goroutine 23 [chan receive]:
fyne.io/fyne/app.watchFile.func1(0xc0000bc460, 0xc0000a81b0, 0x25, 0xc0000a1730, 0xc0000a1740)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/app/settings_desktop.go:42 +0x58
created by fyne.io/fyne/app.watchFile
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/app/settings_desktop.go:41 +0xe7

goroutine 25 [chan receive]:
github.com/s77rt/hashcat%2elauncher.(*hcl_gui_monitor).Init.func1(0xc0000bc4b0, 0xc000104768)
        /home/jean/Downloads/hashcat.launcher-0.3.0/monitor.go:27 +0x31
created by github.com/s77rt/hashcat%2elauncher.(*hcl_gui_monitor).Init
        /home/jean/Downloads/hashcat.launcher-0.3.0/monitor.go:24 +0x60

goroutine 35 [select, locked to thread]:
fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc0000bc410, 0xc00036c000, 0xc0001ea050)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/loop.go:186 +0x10e
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/loop.go:182 +0xbd

goroutine 5 [chan receive]:
fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc0000300c0, 0xc000380000)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/canvas.go:506 +0x47
created by fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/canvas.go:504 +0xa6

goroutine 37 [chan receive]:
main.main.func1(0xc00035f140, 0xc000104580)
        /home/jean/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher/main.go:21 +0x34
created by main.main
        /home/jean/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher/main.go:20 +0x193

goroutine 69 [chan receive]:
fyne.io/fyne/internal/painter.SvgCacheMonitorTheme.func1(0xc00036dd40)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/painter/svg_cache.go:103 +0x34
created by fyne.io/fyne/internal/painter.SvgCacheMonitorTheme
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/painter/svg_cache.go:101 +0x9c
exit status 2`

As soon as I click on choosing dictionary or choosing rules, app also crashes. 

Any idea why?

Thanks

**Comment by s77rt** [comment]
duplicated.
see #7
