### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Jaja51** [s77rt/hashcat.launcher#15]
I've started using the program. It's working very well, congrats.

Here are some suggestions that would be useful:

A way to identify each queue (which algo/dic/rules/set of hashes will be used) and a way to move each queue up and down in the left menu depending on the priority.

What do you think?

**Comment by s77rt** [comment]
Hi @Jaja51 
for the priority feature, currently the order will be as the same order you create the task
if you create task a, b then c => task a will run first then b then c
i understand that you want to be able to control the priority, this has been noted and may be added.

for the first feature request, can you please clarify? (maybe an example?)

**Comment by Jaja51** [comment]
> Hi @Jaja51
> for the priority feature, currently the order will be as the same order you create the task
> if you create task a, b then c => task a will run first then b then c
> i understand that you want to be able to control the priority, this has been noted and may be added.
> 
> for the first feature request, can you please clarify? (maybe an example?)

Maybe something like this?

![hashcat](https://user-images.githubusercontent.com/74815454/99884041-6edb1700-2c2b-11eb-82c1-7b1684aeb2c3.png)

**Comment by s77rt** [comment]
okay, it's clear now,
this has been noted

**Comment by Jaja51** [comment]
The interface is very sleek and the queue system works perfectly. It's going to save me some time. Thank you for the time you put into this software.

**Comment by s77rt** [comment]
glad to hear that this is becoming useful for you ))

**Comment by s77rt** [comment]
Hi,
as for the info, i'm afraid that's not possible now, you have to press the Start button and see the info returned by hashcat in hash type and hash target,

and as for the priority feature i have done this locally, it will be available in the next release

**Comment by s77rt** [comment]
actually there is a way to provide info about a given task and it works just fine (where the task was initially created by hashcat.launcher or just loaded from a .restore file)
the info is going to be a list of arguments that have been passed for the task (and from that you can extract by yourself hashtype, target file, etc...)

**Comment by s77rt** [comment]
Added on v0.4.0
