### ISSUE TITLE
Finding hash algoritms is hard

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#16]
I was going to use SHA-256 (1400). I search but I can't find it in the list. I tried for the number but even with that no founds. What I know does hashcat still support SHA-256 (1400).

It would be nice to search for hashcat hash algoritm by id. Or be able to just add the id to some form of combobox if that is possible.

**Comment by s77rt** [comment]
hi,
i think you are looking for SHA2-256 (1400)
maybe a search by id is good idea :)

**Comment by foordeluxe** [comment]
On hashcat.net list of algos it's sha-256. But as you read from hashcat sha2-256 should maybe be correct. Thanks.

**Comment by s77rt** [comment]
yeah, it just that hashcat.net's algo list is outdated

**Comment by s77rt** [comment]
Now the search works for name and id (starting from v0.4.0)
Closing this for now.
