### ISSUE TITLE
the file browsing gui sucks 

### ISSUE THREAD

**Issue by minanagehsalalma** [s77rt/hashcat.launcher#18]
the tool is really great but browsing and selecting files really sucks!!

**Comment by minanagehsalalma** [comment]
the hash type search is broken too.

**Comment by s77rt** [comment]
Hi,
Unfortunately i can't do much about the file browser for now, hopefully it will get better soon. 
All what you can do now is to arrange your files in directories and make sure that the main directory does have too many siblings for easy access.
I'm still trying to enhance files handling as much as possible if you have any ideas please let me know. 

As for the hash type selector, i don't think it's broken, maybe you just have not set hashcat binaries location (and in the search you should type at least 2 chars to get results)

**Comment by minanagehsalalma** [comment]
> As for the hash type selector, i don't think it's broken, maybe you just have not set hashcat binaries location (and in the search you should type at least 2 chars to get results)

No i have selected the bin file ... should select the exe ?

When i type it shows nothing.

**Comment by s77rt** [comment]
Depends on your os, 
If windows .exe
else  .bin
I think the "hashcat binaries" was misleading?

**Comment by minanagehsalalma** [comment]
> I think the "hashcat binaries" was misleading?

yup.

**Comment by minanagehsalalma** [comment]
also why it shows the bench mark like this and not the cmd one ?
![image](https://user-images.githubusercontent.com/20546638/102078457-a34d8780-3e13-11eb-9c1b-f56a80a7f481.png)

it would be hella great if you can get it to work like this 
https://share.blandyuk.co.uk/apps/

**Comment by s77rt** [comment]
> > I think the "hashcat binaries" was misleading?
> 
> yup.

Okay this has been noted and shall be fixed in the next release.

**Comment by s77rt** [comment]
> also why it shows the bench mark like this and not the cmd one ?
> ![image](https://user-images.githubusercontent.com/20546638/102078457-a34d8780-3e13-11eb-9c1b-f56a80a7f481.png)
> 
> it would be hella great if you can get it to work like this
> https://share.blandyuk.co.uk/apps/

Can you please send a screenshot or a gif of what you are referring to.

**Comment by s77rt** [comment]
i don't know what you are referring to exactly, if you mean that every task (including benchmark) will start in a new cmd, well it won't
hashcat.launcher not only launch a hashcat instance but also controls it, all actions must be taken from inside the software.

**Comment by minanagehsalalma** [comment]
> i don't know what you are referring to exactly, if you mean that every task (including benchmark) will start in a new cmd, well it won't
> hashcat.launcher not only launch a hashcat instance but also controls it, all actions must be taken from inside the software.

But i want to see whats happening. And control it with just clicks not commands at the same time.

**Comment by s77rt** [comment]
are talking about tasks in general or just the benchmark?

**Comment by minanagehsalalma** [comment]
> are talking about tasks in general or just the benchmark?

In general.

**Comment by s77rt** [comment]
you can do that already,
once you create a task you can pause, resume, stop,,,etc the task as you wish

**Comment by minanagehsalalma** [comment]
> you can do that already,
> once you create a task you can pause, resume, stop,,,etc the task as you wish

How can i add wordlists ?

**Comment by s77rt** [comment]
first you need to set the Mode to: Dictionary
and then in the entry you can either pastes files locations one per line or just click on the "+" button to add a file

**Comment by minanagehsalalma** [comment]
> https://share.blandyuk.co.uk/apps/

Have you tested this one ? 

Just try to get it to be like this ... this all what's missing.

**Comment by s77rt** [comment]
the software are probably not the same
i think it works a bit different here
1. select the mode
2. select the wordlists
3. click on the launch button

**Comment by minanagehsalalma** [comment]
It's also missing the season restore option.

**Comment by s77rt** [comment]
yes, this will be fixed, see #12

**Comment by s77rt** [comment]
You may want to check the new version v0.4.0
it fixes the misleading "hashcat binaries" by just stating "hashcat"
and it made it easy to handle multiple tasks
and for the dictionaries selection behavior i can't do much about now but you can follow on #5 for any changes (or post your suggestions there)

let's keep this issue just for the "file browser", which is also something i can't change it much currently but soon hopefully it will get much better

**Comment by s77rt** [comment]
Hi,
kindly checkout v0.5.0
I added the option to switch between dialog handler (file browser gui) to either use the os dependent or the native one;
by default it will use the os dependent as it's cleaner and easier to use

**Comment by s77rt** [comment]
If you don't want to receive notifications about this just close the issue, before that let me point that your issue can be easily fixed by using a proper value for scaling; go to Options and change the value on Scaling.

here a video shows how it should look in general

https://user-images.githubusercontent.com/16493223/110677091-0cefee80-81d5-11eb-8e33-3007bd30f89f.mp4

**Comment by s77rt** [comment]
this is kinda not related to hashcat.launcher itself but to the framework
did you manage to get it working after changing the scaling value?

**Comment by minanagehsalalma** [comment]
> this is kinda not related to hashcat.launcher itself but to the framework
> did you manage to get it working after changing the scaling value?

nope i was able to see the other options at 50% scale but that was so hard on my eyes.

**Comment by s77rt** [comment]
Okay understood, will work on a patch asap
thanks for the feedback

**Comment by s77rt** [comment]
> Okay understood, will work on a patch asap
> thanks for the feedback

Moving this to #24 

Closing the current issue and the file browser is fixed now
