### ISSUE TITLE
Filtering by hash algoritm by id issue

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#19]
When trying to find by id, like md5 have 1 character. It notice me that I need to use at least 2 chars to filter.
I know I can just write down md5, but would be faster with just writing 0 and use that.

**Comment by s77rt** [comment]
Hi,
i noticed that at the time of development, but it's not worth it to make the search slow (by removing the min chars requirements) just for one algo, typing md5 is not that hard task after all :)

**Comment by s77rt** [comment]
if the provided answer was acceptable kindly close the issue.

**Comment by foordeluxe** [comment]
Yes I can live with  writing md5 :)
