### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by 737simpilot** [s77rt/hashcat.launcher#2]
Running a benchmark or the launcher I get an error about a bad file descriptor.
Errors:
stdin: Bad file descriptor

**Comment by s77rt** [comment]
Hi,
Can you attach a screenshot?
And are you able to use the software? (i mean to crack hashes, instead of just a benchmark)
Also please let me know your OS info

**Comment by 737simpilot** [comment]
No, I can't crack a hash. Windows 7 64. If I select CPU instead of GPU I don't get any Info except an error about bad file descriptor no devices found/left. 


![1](https://user-images.githubusercontent.com/16517998/82815162-d8819080-9e55-11ea-8fc1-24bf43df990c.jpg)


![2](https://user-images.githubusercontent.com/16517998/82815176-df100800-9e55-11ea-80e9-8f5733377cd0.jpg)


![3](https://user-images.githubusercontent.com/16517998/82815188-e7684300-9e55-11ea-9df5-83453d04804e.jpg)


![4](https://user-images.githubusercontent.com/16517998/82815194-ed5e2400-9e55-11ea-9270-707ae580063c.jpg)

**Comment by 737simpilot** [comment]
I chose Keepass as the hash type.

**Comment by s77rt** [comment]
I think there is two issues here; for one you are using an unsupported hashcat version, please use the latest beta available at https://hashcat.net/beta/
and then try to crack a hash.

You may also see the "Bad file descriptor" error message but it may also work in the same time... 

please let me know the results

**Comment by 737simpilot** [comment]
Still have the same error, but slightly different message for both GPU and CPU. Can't crack a hash either. 



![gpu](https://user-images.githubusercontent.com/16517998/82816772-f997b080-9e58-11ea-8fdd-53bcbb53bb1a.jpg)


![cpu](https://user-images.githubusercontent.com/16517998/82816782-00262800-9e59-11ea-93ff-4e2943255056.jpg)

**Comment by s77rt** [comment]
can you try to crack a hash and report back the results?

**Comment by 737simpilot** [comment]
![1](https://user-images.githubusercontent.com/16517998/82817575-74ad9680-9e5a-11ea-8947-3affc7989e06.jpg)

**Comment by s77rt** [comment]
This seems to be a Windows 7 related issue, can you try with a win8/win10 os ?

**Comment by 737simpilot** [comment]
Only in VMware. Will I get full GPU/CPU support in VMware Workstation Player?

**Comment by s77rt** [comment]
I don't think so, hashcat.launcher itself may not work in a virtual env (due to graphical driver issues)

**Comment by 737simpilot** [comment]
Yep, it won't detect the GPU/CUDA and all that, but this time the hash selection shows up in Windows 10. What I'll do one day is install Windows 10 to another hard drive and go from there.

**Comment by s77rt** [comment]
the hash selection will always shows up because now you are using a supported hashcat version.
Since the software is working insid the VMware can you try to benchmark? (and see if you get the "Bad file descriptor" error msg)

**Comment by s77rt** [comment]
any update on this?

**Comment by 737simpilot** [comment]
Sorry, I have yet to install Windows 10 on another hard drive for testing.

**Comment by s77rt** [comment]
Closing this issue for now.
Feel free to re-open if any further help is needed
