### ISSUE TITLE
Creating new document to save founds inside

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#20]
Before you could create a new file to save founds. Somehow that was a issue for Linux. And the new interface needs me to make a found file before I can load it. Is it possible to maybe add a feature to create a new document inside the interface?

**Comment by s77rt** [comment]
Actually that's already possible, i think it's just somehow hard to notice
when you open the file browser dialog, next to the "Close" button there is a text field, just type a new file name there and click on "Save"
if the file does not exist it will be created.

**Comment by foordeluxe** [comment]
I can't find this in the new interface.

**Comment by foordeluxe** [comment]
I found it now. Didn't know this existed but I edited the text at left and was able to create a new file. I think this can be closed now.

**Comment by s77rt** [comment]
Cool :)
