### ISSUE TITLE
I just need to say thanks.

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#21]
I'm so happy that you continue on this project and add new features. Thanks so much. I'm on Linux at the moment and everything works good since you changed the interface. Thanks so much. I think I can't thanks enough.

**Comment by s77rt** [comment]
You are so welcome
Your issues are helping the app becomes better :)

**Comment by rmartensen** [comment]
This tool is very useful and makes my life a bit more easy and I also want to say thanks devs <3
I would like to make a donation to this project too, how could I do that?

**Comment by s77rt** [comment]
@rmartensen
You can donate:
PayPal: https://www.paypal.com/donate/?cmd=_donations&business=paypal%40yalagroup.co.uk&currency_code=USD
BTC: 3QnabPPhS5sGYjvSMxHv2krzdj3pW9Qdxs

Thank you for your interest
