### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by s77rt** [s77rt/hashcat.launcher#24]
The app is often too big (by default) or even too small when trying to change the scaling value

**Comment by foordeluxe** [comment]
Found out this too. I have not the biggest monitor but scaling to 80% fixed this for me. The new UI is really huge.

**Comment by s77rt** [comment]
a quick and a temporarily hack for custom scaling:
for Windows users:
`C:\Users\USERNAME\AppData\Roaming\fyne`

for Linux users:
`/home/USERNAME/.config/fyne`

you will find a file named **settings.json** open the file and edit the scale value as you see fit

**Comment by s77rt** [comment]
Fixed on [v0.5.1](https://github.com/s77rt/hashcat.launcher/releases/tag/v0.5.1)
