### ISSUE TITLE
Where did size of each dictionary go?

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#26]
What I remember you could see the size of each dictionary in the dictionary window.
It's not needed to be there, but for me it was nice to know the size.

**Comment by s77rt** [comment]
it's still there,
there is a scroll bar at the bottom, use it to scroll horizontally you will see the size next to each dictionary

**Comment by foordeluxe** [comment]
Oh did see this now. I think this can be closed now.
