### ISSUE TITLE
90 Celsius hit on abort

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#27]
I wonder should hashcat pause, stop or make an option to restore when hit 90 Celsius?
For me the whole program crashed and then I couldn't find anything to restore and I needed to start from the beginning.
I have never hit 90 Celsius before, so this is new for me.

**Comment by s77rt** [comment]
if the temp abort is reached then hashcat abort and you should be able to restore the task (if there is a restore point availble)
but the program is not supposed to crash, so this may be a bug,
was your task running for a long time?
are you sure the temp hit 90 °C ?
can you replicate this? (try set the temp abort to 70 °C or so to make the scenario easier to replicate)

**Comment by foordeluxe** [comment]
I was running the task a long time. Because the rule is big.
I can't make hashcat.launcher to crash this time, it just aborted when I used 70 as minimum.
Could be Linux that did the crash too.

**Comment by s77rt** [comment]
okay, let me know if this happen again

**Comment by foordeluxe** [comment]
It doesn't crash for me. And I have been cracking different days. So I close this now.
