### ISSUE TITLE
The arguments from restore window is bugged out.

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#28]
Like in the title. To see the restore argument in restore window you can't see everything. It's like 1 line you can see.
Here is a screenshot: https://gofile.io/d/Ac79La

**Comment by s77rt** [comment]
It's not really a bug, but i will figure out a way to make the arguments take the rest of the remaining space

**Comment by foordeluxe** [comment]
Oh. I thought it was a bug. I can still see whats inside. But would be nice to be able to see more.

**Comment by s77rt** [comment]
okay understood, shall be fixed in the next release.
for now as a temporarily solution: restore the task, and view the arguments from the tasks tab (it's not really a good solution but it's better than reading line by line in the restore modal)

**Comment by s77rt** [comment]
Fixed by https://github.com/s77rt/hashcat.launcher/commit/d87570962ba4a50ef5b56a62c106584ab49f1775
(the fix will be available in the next released version or you can compile the code in [master branch](https://github.com/s77rt/hashcat.launcher/tree/master) to get the fix now)

**Comment by s77rt** [comment]
Closing this as it's fixed.

PS: [v0.5.1](https://github.com/s77rt/hashcat.launcher/releases/tag/v0.5.1) is available now and includes the fix.
