### ISSUE TITLE
Recent Restore points, a way to clear them

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#29]
I have tried to delete all files that hashcat.launcher use. But the recent restore points keep stay in the window. And I have no way to clear them. Would be nice to be able to do this.

**Comment by s77rt** [comment]
the restore files are created by hashcat not hashcat.launcher if you want to delete a restore file delete it from within hashcat
(the files are named exactly as you see them), maybe i will add a delete button in hashcat.launcher too

**Comment by foordeluxe** [comment]
it's weird. because I delete them. And still they came back into the restore window. Are they placed somewhere else too?

**Comment by s77rt** [comment]
no, only on hashcat folder
maybe you have two hashcat folders and you are deleting files that belongs to the wrong one?

**Comment by s77rt** [comment]
Any update on this?

**Comment by foordeluxe** [comment]
I deleted all files. And now they are gone from the list.

**Comment by s77rt** [comment]
You only need to delete .restore files to remove them from the list.
v0.5.1 now includes a delete button for restore files.

If this is resolved kindly close the issue

**Comment by foordeluxe** [comment]
Both manually and from the tool. This works. Thanks so much.
