### ISSUE TITLE
.bin not operating with hash type search function

### ISSUE THREAD

**Issue by Duocast** [s77rt/hashcat.launcher#3]
Although the proper .bin is selected and loaded fine, the "Hash Type" drop-down does not populate while looking up hash types.

**Comment by s77rt** [comment]
Hi,

Can you please specify hashcat version + OS

**Comment by Duocast** [comment]
Hashcat 5.1 running through PowerShell 7 on Windows 10.

**Comment by s77rt** [comment]
@Duocast can you specify which version of hashcat exactly?
you may be using an unsupported one, try using v6.0.0

**Comment by Duocast** [comment]
Looks like that fixed it, 5.1 won't work right but using 6.0 does find the
hash type for selection.

**Comment by Duocast** [comment]
Although it does seem I have encountered an error.
The system GPU this is running on is an nVidia 1660 Ti with 16 GB of RAM
and a 9th gen i7.

See screenshots

**Comment by Duocast** [comment]
Here is a better look at the hardware configuration.

CUDA Info:
==========

CUDA.Version.: 11.0

Backend Device ID #1 (Alias: #2)
  Name...........: GeForce GTX 1660 Ti
  Processor(s)...: 24
  Clock..........: 1590
  Memory.Total...: 6144 MB
  Memory.Free....: 5163 MB

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 1.2 CUDA 11.0.186

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: GeForce GTX 1660 Ti
    Version........: OpenCL 1.2 CUDA
    Processor(s)...: 24
    Clock..........: 1590
    Memory.Total...: 6144 MB (limited to 1536 MB allocatable in one block)
    Memory.Free....: 5120 MB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 451.22

OpenCL Platform ID #2
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) OpenCL HD Graphics
  Version.: OpenCL 2.1

  Backend Device ID #3
    Type...........: GPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) UHD Graphics 630
    Version........: OpenCL 2.1 NEO
    Processor(s)...: 24
    Clock..........: 1150
    Memory.Total...: 6492 MB (limited to 3246 MB allocatable in one block)
    Memory.Free....: 6428 MB
    OpenCL.Version.: OpenCL C 2.0
    Driver.Version.: 27.20.100.8280

**Comment by s77rt** [comment]
v5.1.0 is not supported, but a beta version v5.1.0+1774 and higher (including v6.0.0) is supported.

"Although it does seem I have encountered an error. ... See screenshots"
No screenshots were attached...

**Comment by ajtazer** [comment]
![image](https://user-images.githubusercontent.com/37796611/86820263-6a5ff880-c0a6-11ea-95a1-69ec07dc1bd7.png)
![image](https://user-images.githubusercontent.com/37796611/86820380-97aca680-c0a6-11ea-8275-e3ffc3e32ad1.png)
NO RESULT COMES IN DROPDOWN MENU

My Specifications:
```
OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Advanced Micro Devices, Inc.
  Name....: AMD Accelerated Parallel Processing
  Version.: OpenCL 2.1 AMD-APP (2841.19)

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: Baffin
    Version........: OpenCL 2.0 AMD-APP (2841.19)
    Processor(s)...: 14
    Clock..........: 1000
    Memory.Total...: 4096 MB (limited to 3264 MB allocatable in one block)
    Memory.Free....: 4032 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 2841.19

  Backend Device ID #2
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: gfx902
    Version........: OpenCL 2.0 AMD-APP (2841.19)
    Processor(s)...: 8
    Clock..........: 1201
    Memory.Total...: 2936 MB (limited to 2387 MB allocatable in one block)
    Memory.Free....: 2872 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 2841.19 (PAL,HSAIL)
```

**Comment by s77rt** [comment]
@ajtazer 
You should go to options and set the binary location of hashcat then try again

**Comment by ajtazer** [comment]
![image](https://user-images.githubusercontent.com/37796611/86822097-ce83bc00-c0a8-11ea-9e29-2a9b6d411b6b.png)
BINARY LoCATION is FINE

**Comment by s77rt** [comment]
Will consider this issue as non-qualified issue. (bad usage)
If you need further help reopen or open a new issue :)
