### ISSUE TITLE
Remove added files (dictionaries and rules)

### ISSUE THREAD

**Issue by s77rt** [s77rt/hashcat.launcher#32]
Find a way to efficiently remove added files (dictionaries and rules)
- Must be able to remove individual files
- Must be able to remove all files in a folder

**Comment by foordeluxe** [comment]
Any update on this feature? Would be really nice to have it now.

**Comment by s77rt** [comment]
in version v1.0.0 files are being automatically loaded from a folder
and the files selection is in my opinion faster and easier

closing this for now as it's no longer applicable
reopen if needed
