### ISSUE TITLE
A way to disable $HEX converting

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#33]
Like title, a way to disable $HEX converting. Or if there is a command-line option already which I don't know about.

**Comment by s77rt** [comment]
Hi,
i think you mean in the output format, right?
try with this command (add to the extra args input): `--outfile-autohex-disable`

> https://hashcat.net/wiki/doku.php?id=hashcat
> --outfile-autohex-disable Disable the use of $HEX[] in output plains

**Comment by foordeluxe** [comment]
Thanks.
