### ISSUE TITLE
Tasks that have been paused crack the same hash again.

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#35]
Look how this is done, at my new post.

**Comment by s77rt** [comment]
this does not seem to be a hashcat.launcher problem
can you try with hashcat itself and see if you get the same issue

**Comment by foordeluxe** [comment]
these steps do I do to get this:
0) run hashcat.launcher and make a task.
1) make a new task and crack passwords.
2) When finished go back to the first task and run it.

This will not update the current left list, it will crack already cracked hashes. I don't know if it's hashcat.launcher or if it's hashcat itself.

**Comment by foordeluxe** [comment]
Yes it must be. I don't think hashcat.launcher have these issues.
