### ISSUE TITLE
cannot select Hash Type:

### ISSUE THREAD

**Issue by trnepalla** [s77rt/hashcat.launcher#37]
yes, the hashcat exe (6.2.2) location is correctly configured  ,,

thanks.

**Comment by trnepalla** [comment]
use hashcat 6.1.1 :)

**Comment by s77rt** [comment]
i will make a new release later today, (that supports hashcat version 6.2)
for now you can try build from source https://github.com/s77rt/hashcat.launcher#building-from-source
or use hashcat 6.1

**Comment by s77rt** [comment]
hashcat.launcher v0.5.2 has been released
