### ISSUE TITLE
Error: no hashes load

### ISSUE THREAD

**Issue by Saryon8** [s77rt/hashcat.launcher#38]
Hi

I use hashcat with your launcher. I was trying to recover the access to my external disk (the code was on a paper that unfortunatly got some coffee on it, but i still can read most of it, only 2 on 20 caracter was lacking). The hack was successfull but i can't find the password in the output. Trying to find it, i must have done a mistake because now every time i try to attack, i have the following error message "error: no hashes load". I try to redownload everything from the start but no luck.

How can i get hashcat working again? And where can i find the password then?

**Comment by s77rt** [comment]
Hi
have you checked the pot file?

**Comment by Saryon8** [comment]
How can i do that?

**Comment by s77rt** [comment]
in hashcat folder there will be a file hashcat.potfile
open that file in a text editor and see if you can find your hash there

**Comment by Saryon8** [comment]
I just check it and there is no such file in the directory. And there is a bunch of .outfiles folder but all are empty. I think that's maybe link to the error "no hashes load".

**Comment by s77rt** [comment]
can you send a screenshot

**Comment by Saryon8** [comment]
Yes, here you have:

![Screenshot hashcat folder](https://user-images.githubusercontent.com/86876467/124362676-c0726800-dc36-11eb-95a6-5fe3a559b8d1.png)

**Comment by s77rt** [comment]
sorry i meant a screenshot where you see the error (in hashcat.launcher to go tasks and go to the task's journal)

**Comment by Saryon8** [comment]
Here:

![Screenshot hashcat](https://user-images.githubusercontent.com/86876467/124363083-6fb03e80-dc39-11eb-8aa1-429f700e48c0.png)

**Comment by s77rt** [comment]
possibly you are using the wrong hash mode

**Comment by Saryon8** [comment]
I think about that but i was working before with the one i use now.

**Comment by Saryon8** [comment]
I think about that, but it was working before with the same hashtype (and also as i had created the file myself before i know what type i use), so i don't understand.

**Comment by s77rt** [comment]
i don't know what went wrong exactly, but you can try again and make sure to select an output file so you know where you'd fine the password

**Comment by Saryon8** [comment]
When it was working, i always select a output file, but there was no password on it anyway, i don't understand why and according to you that's not normal.

**Comment by s77rt** [comment]
Can you try with a pre known hash value, just to make sure things are working as expected

**Comment by Saryon8** [comment]
I think i understand the problem. In my opinion, it keeps saying me that because i already hack the password, even if i don't find where it's written. 

I try to make a copy of the encrypted file and to hack on this copy. I have no longer the no hash error but the "no such files or directory" one. 

![Screenshot hashcat2](https://user-images.githubusercontent.com/86876467/125159441-a1fcf700-e177-11eb-8188-6a69091e5e19.png)

**Comment by s77rt** [comment]
even if you make a copy you won't see the hash if it's already cracked, first go to settings and in the Extra Args field add: `--potfile-disable`

as for your the new error, it's because the hash file cannot be accessed.
perhaps `C:\Users\basti\Desktop\Prive`does not exists?

**Comment by foordeluxe** [comment]
> Yes, here you have:
> 
> ![Screenshot hashcat folder](https://user-images.githubusercontent.com/86876467/124362676-c0726800-dc36-11eb-95a6-5fe3a559b8d1.png)
> 
> Forget to say i'm in Windows 10.

Where did you place hashcat.launcher? Maybe it's bugged and added the pot-file in the folder where you have hashcat.launcher extracted.

**Comment by Saryon8** [comment]
"as for your the new error, it's because the hash file cannot be accessed.
perhaps C:\Users\basti\Desktop\Privedoes not exists?"

It exists, i even point where this it to the software, i don't understand how he can't find it! But if that's a copy and it doesn't work with a copy, that's maybe the point. 

I put hashcat folder on the desktop and hashcat laucher is on the desktop too (not in hashcat folder if that's the question).

**Comment by Saryon8** [comment]
I may have find the problem: the files is title "Privé" with an accent but in hashcat journal it appears at "Prive" without accent.

**Comment by s77rt** [comment]
can you change the files name? use a clear alphanumeric name and try again

**Comment by Saryon8** [comment]
It seems to work and to have found the password, where i go next to recover it?

**Comment by s77rt** [comment]
you should find the password in the output file that you selected

**Comment by Saryon8** [comment]
There is only this in output file:

E:\Sauvegarde\Documents\Prive:$HEX[627238383c47377e357b286a6147586344553a36]

I see no password there.

**Comment by s77rt** [comment]
the passoword is in hex format, just decode it
that should be the password you are looking for: `br88<G7~5{(jaGXcDU:6`

**Comment by Saryon8** [comment]
That's exactly that, thank you for the help.

**Comment by s77rt** [comment]
You are welcome, i think we can close this case now.
(for easy to read) I have opened a new issue regarding special characters in filenames

**Comment by Saryon8** [comment]
Yes you can close it.
