### ISSUE TITLE
OS requirement

### ISSUE THREAD

**Issue by 737simpilot** [s77rt/hashcat.launcher#39]
Does this UI interface still require Windows 10?

**Comment by s77rt** [comment]
Hi
I have only tested with Windows 10
Are you facing any issue with an older windows version?

**Comment by 737simpilot** [comment]
No. I just tried to run this program some time ago and you told me it would only run in Windows 10. I don't run Windows 10 right now, only Windows 7 so I wanted to know if the recent updates made it so that this would run in Windows 7. Not sure why it would be Windows 10 dependent. 

One day when I feel like it I'll strip 10 with NTLite and compile using Windows 10 AME. Not in the mood to do that right now though.

**Comment by s77rt** [comment]
You can try run a [pre-built release](https://github.com/s77rt/hashcat.launcher/releases/latest) and see if it works
I don't have any idea why this won't run under windows 7, it should work as long as it's a 64bit version (although not tested)

**Comment by s77rt** [comment]
Please also try with the latest version v1.0.0 (alpha version is available)
Closing this for now, reopen if needed
