### ISSUE TITLE
How to select devices manual by id?

### ISSUE THREAD

**Issue by LorDo** [s77rt/hashcat.launcher#40]
How to select devices manual by id? I need it because i have intergrated into cpu "GPU" and i cant start work only on external grapich cards because intergated card and external cards have same category "GPU".

**Comment by s77rt** [comment]
Hi,
This is actually a missing feature, that i have just implemented https://github.com/s77rt/hashcat.launcher/commit/706293d95f55a6a61a0abcc16759dedee6ad3c8e
Please try using the master branch (and build from source)

**Comment by LorDo** [comment]
Can u paste release a compilled version? Im use windows

**Comment by s77rt** [comment]
[hashcat.launcher_dev_linux.zip](https://github.com/s77rt/hashcat.launcher/files/6834651/hashcat.launcher_dev_linux.zip)
[hashcat.launcher_dev_windows.zip](https://github.com/s77rt/hashcat.launcher/files/6834654/hashcat.launcher_dev_windows.zip)

**Comment by LorDo** [comment]
Something wrong because im select 1,2,3,4 and start work but i get falied with error: 
![image](https://user-images.githubusercontent.com/1587284/126064521-46f8531d-8db7-4167-ab09-34b1926de946.png)
But how? im not selected 5 or 6 in task!

**Comment by s77rt** [comment]
can you paste the output of devices info here?

**Comment by LorDo** [comment]
Yes, look

CUDA Info:
==========

CUDA.Version.: 11.4

Backend Device ID #1 (Alias: #7)
  Name...........: NVIDIA GeForce GTX 1080 Ti
  Processor(s)...: 28
  Clock..........: 1683
  Memory.Total...: 11264 MB
  Memory.Free....: 10227 MB

Backend Device ID #2 (Alias: #8)
  Name...........: NVIDIA GeForce GTX 1080 Ti
  Processor(s)...: 28
  Clock..........: 1683
  Memory.Total...: 11264 MB
  Memory.Free....: 10228 MB

Backend Device ID #3 (Alias: #9)
  Name...........: NVIDIA GeForce GTX 1080 Ti
  Processor(s)...: 28
  Clock..........: 1683
  Memory.Total...: 11264 MB
  Memory.Free....: 10227 MB

Backend Device ID #4 (Alias: #10)
  Name...........: NVIDIA GeForce GTX 1080 Ti
  Processor(s)...: 28
  Clock..........: 1683
  Memory.Total...: 11264 MB
  Memory.Free....: 10227 MB

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) OpenCL HD Graphics
  Version.: OpenCL 2.1 

  Backend Device ID #5
    Type...........: GPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) HD Graphics 610
    Version........: OpenCL 2.1 NEO 
    Processor(s)...: 12
    Clock..........: 1050
    Memory.Total...: 4791 MB (limited to 2395 MB allocatable in one block)
    Memory.Free....: 4727 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 27.20.100.8681

  Backend Device ID #6
    Type...........: GPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) HD Graphics 610
    Version........: OpenCL 2.1 NEO 
    Processor(s)...: 12
    Clock..........: 1050
    Memory.Total...: 4791 MB (limited to 2395 MB allocatable in one block)
    Memory.Free....: 4727 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 27.20.100.8681

OpenCL Platform ID #2
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 3.0 CUDA 11.4.56

  Backend Device ID #7 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce GTX 1080 Ti
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 28
    Clock..........: 1683
    Memory.Total...: 11264 MB (limited to 2816 MB allocatable in one block)
    Memory.Free....: 10432 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 471.11

  Backend Device ID #8 (Alias: #2)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce GTX 1080 Ti
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 28
    Clock..........: 1683
    Memory.Total...: 11264 MB (limited to 2816 MB allocatable in one block)
    Memory.Free....: 10432 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 471.11

  Backend Device ID #9 (Alias: #3)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce GTX 1080 Ti
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 28
    Clock..........: 1683
    Memory.Total...: 11264 MB (limited to 2816 MB allocatable in one block)
    Memory.Free....: 10432 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 471.11

  Backend Device ID #10 (Alias: #4)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce GTX 1080 Ti
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 28
    Clock..........: 1683
    Memory.Total...: 11264 MB (limited to 2816 MB allocatable in one block)
    Memory.Free....: 10432 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 471.11

**Comment by s77rt** [comment]
in hashcat.launcher click on View Arguments and paste the content here

**Comment by LorDo** [comment]
Yes look

--session=hcl_1626687540996243900_19
--status
--status-timer=90
-O
--hwmon-temp-abort=75
--markov-threshold=0
-w4
-m1800
-a0
C:\Users\User\Desktop\DECRYPT.txt
--separator=:
-d
1,2,3,4
-D
2
-o
C:\Users\User\Desktop\OUT.txt
--outfile-format=1,2,3
--logfile-disable
--opencl-device-types=2
E:\dict.txt
E:\out.txt

**Comment by s77rt** [comment]
this seems like a hashcat bug, it's checking all backend devices before starting..., can you get this working using hashcat only?
also remvoe `opencl-device-types` from Extra Args since there is a dedicated entry for that now.

**Comment by s77rt** [comment]
Added.
Closing for now.
