### ISSUE TITLE
A way to add new wordlist at top of the dictionaries list

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#41]
Like the title. I use your dictionaries file for path to my dictionaries I use. I load the list and then crack with them. 
So if I open up the dictionaries list in hashcat.launcher there is around 130 lines of them. I want maybe to test another list and add that into the dictionaries list. 
But now I need to scroll to the whole bottom because of all my dictionaries is loaded. 
What should be good is that the new list got added to the top of my 130 lines of dictionaries.

I have seen that you was going to add a way to delete and clear dictionaries from the list, but if you don't have enough time to do this. It would be nice to get the new dictionary to the top of the list.

**Comment by s77rt** [comment]
so the issue is can't easily add new dictionaries due to the long list of old loaded dictionaries, is that right?

**Comment by foordeluxe** [comment]
> so the issue is can't easily add new dictionaries due to the long list of old loaded dictionaries, is that right?

Yes. It's a lot of files to scroll down to bottom.

**Comment by foordeluxe** [comment]
This is not needed anymore. There are two lists, one with Dictionaries Selection and one with the Selected Dictionaries. I have lately been using the Selected Dictionaries list instead.
