### ISSUE TITLE
Task Failure 

### ISSUE THREAD

**Issue by anhdt061091** [s77rt/hashcat.launcher#44]
Hi 
My name is Tuan Anh , 
I'm trying to install GUI for hashcat and I found this source code of yours. I tried to install hashcat.launcher v0.5.2 on my computer (ubuntu 20.04). However, after trying to run it, it shows a Task failed error, I don't know why and it doesn't show up in the error log either. Can you help me take a look?
![Screenshot from 2021-09-23 09-58-59](https://user-images.githubusercontent.com/39880305/134448793-149799ca-af24-4858-b1a9-db7be84ae7f6.png)
![Screenshot from 2021-09-23 09-59-51](https://user-images.githubusercontent.com/39880305/134448798-a8ec9d1f-c35f-4bca-86d4-521f7c80ba97.png)

**Comment by s77rt** [comment]
Hi
Click on Journal to see the log

**Comment by anhdt061091** [comment]
Thanks for your reply 

I can see the log in the Jounal, but i don't know how can i fix that . 
I can use the command to get hashcat working , but when i use hashcat.launcher i get this error, can you help me to fix it ? 

![Screenshot from 2021-09-23 10-21-37](https://user-images.githubusercontent.com/39880305/134450786-83846d0e-6055-4d4f-8309-a288592bb947.png)

**Comment by s77rt** [comment]
seems you are trying against a hashlist that's already cracked
try with another hash

**Comment by anhdt061091** [comment]
Thank you so much for your support

**Comment by s77rt** [comment]
you are welcome!
if all is okay please close the issue.

**Comment by anhdt061091** [comment]
Hi 
sorry i have 2 more question 
1 - i download your source code with git clone , after that , i install golang and use command make to run . But i have an
![Screenshot from 2021-09-24 14-56-49](https://user-images.githubusercontent.com/39880305/134639337-1a291838-021a-485e-b242-202252890129.png)
 error 
2 - After decrypting the file with hashcat.launcher, where will the decryption pass be stored?

Thank you so much

**Comment by s77rt** [comment]
1. just realised that the [make file is broken](https://github.com/s77rt/hashcat.launcher/issues/45), here is an alternative:
```
cd hashcat.launcher
go generate
cd cmd/hashcat.launcher/
go build
```

2. to the output file if set and/or to hashcat pot file

**Comment by anhdt061091** [comment]
thank you so much for your support
