### ISSUE TITLE
Newest Alpha wont run on Linux

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#47]
Like in title. The stable release works when just clicking on the file. The Alpha doesn't even run. It does nothing.

OS: Linux
Distro: Ubuntu 20.04.03
Kernel: 5.4.0

**Comment by s77rt** [comment]
the new version's frontend relies on a chromium based software such as chrome or chromium, etc...
try install chrome if not installed, also try to run the software from terminal to see if there is any errors

**Comment by foordeluxe** [comment]
Ok. Chrome installed, didn't work.
Tested file from terminal and got This:
```./hashcat.launcher: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./hashcat.launcher)```

**Comment by s77rt** [comment]
alright,
you either install glibc 2.32 (or higher) or recompile hashcat.launcher

**Comment by foordeluxe** [comment]
I tried to recompile hashcat.launcher and got this error:
```Downloading Dependencies: github.com/s77rt/hashcat.launcher imports embed: malformed module path "embed": missing dot in first path element make: *** [Makefile:28: dep] Error 1```

**Comment by s77rt** [comment]
probably due to an old golang version
upgrade golang and try again

**Comment by foordeluxe** [comment]
I only get errors after errors and need to install more and more stuff just to build this. I think I will stay on the old version instead.

**Comment by s77rt** [comment]
only golang and npm are needed
golang for the software itself and npm to build the frontend
can you share what errors you are getting

**Comment by foordeluxe** [comment]
Still getting the same error.
