### ISSUE TITLE
Current dictionary in tasklist

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#53]
Yes I used to look which dictionary that the old version of hashcat.launcher used in tasks. Now is this gone, is there a way to add this back again? Or maybe it's not necessary?

**Comment by s77rt** [comment]
the old version used to extract info from the regular hashcat output
starting with v1 info are extracted from hashcat json formatted output which does not currently support such info

will add the info on hashcat.launcher once implemented in hashcat
https://github.com/hashcat/hashcat/issues/3061

**Comment by foordeluxe** [comment]
Thanks for the information.

**Comment by s77rt** [comment]
Added in [v1.0.0](https://github.com/s77rt/hashcat.launcher/releases/tag/v1.0.0)

Note: you also need the latest hashcat (anything after https://github.com/hashcat/hashcat/pull/3067)

**Comment by s77rt** [comment]
the stats are in the same column as progress info, there is an info circle icon, hover on it
![guess](https://user-images.githubusercontent.com/16493223/147112682-da9f5226-3bdb-46a6-97b5-f5970f3d8925.png)

**Comment by foordeluxe** [comment]
Downloaded latest and it works good.

**Comment by s77rt** [comment]
Thanks for the feedback
