### ISSUE TITLE
Arguments with too many dictionaries cuts off window

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#56]
Like the title. When clicking on Arguments in tasklist and have too many dictionaries, the whole window get cut off.
Image: https://i.ibb.co/rxT3nmN/2021-12-18-00-57.png

**Comment by s77rt** [comment]
Fixed by https://github.com/s77rt/hashcat.launcher/commit/c132b8d911bae9266cde8b4f3079af201074abf7

**Comment by foordeluxe** [comment]
Thanks, This is now fixed.
