### ISSUE TITLE
Other color on finished tasks dot

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#58]
When You have not run a task, it will have a grey dot before. When quit the task it's a red dot. When paused orange, when starting blue.
What about a green dot when it's finished? I know that the text shows 100%. But would make more sense when it's green.

**Comment by s77rt** [comment]
the green color is reserved for "Cracked" status
maybe we can choose another color for "Exhausted" status

**Comment by foordeluxe** [comment]
Yes there would be nice for Exhausted.

**Comment by s77rt** [comment]
Any suggestions on what color to choose?

**Comment by foordeluxe** [comment]
I have no idea about the color.

**Comment by foordeluxe** [comment]
I was thinking about pink. But if you want to use something else do that. And I don't know if pink is already used.

**Comment by s77rt** [comment]
Changed to pink.
please try and let me know

**Comment by foordeluxe** [comment]
Maybe it's only me, but red and pink looks the same for me eyes. Didn't think about this when writing about pink.

**Comment by s77rt** [comment]
they look pretty different to me
when in doubt, click on the task, next to it's id you can see the status written if it's "Quit" or "Exhausted"
