### ISSUE TITLE
Save config files in the same folder as hashcat.launcher

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#59]
Right now does my config files saves automatic in Downloads. Not a place that people would look for their config files. It would be better if they was saved in the folder where hashcat.launcher is inside.

**Comment by s77rt** [comment]
can be done, but saving the configs in the same directory may not be ideal, perhaps it's better to save such configs in a separated folder

**Comment by foordeluxe** [comment]
Yes a separated folder would be good. Should I save them there or is it possible for the tool to do this?

**Comment by s77rt** [comment]
done, please check the beta version

**Comment by foordeluxe** [comment]
Works great.
