### ISSUE TITLE
Some times the GUI become transparency

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#6]
Like in title. Some times when I'm not on my computer and everything has been finished it will be a X - Title and the window will become transparency. When I see this again I will take a screenshot. I don't know why this is happening.

**Comment by s77rt** [comment]
I didn't notice this, a screenshot would be much helpful :)

**Comment by s77rt** [comment]
Closing this for now.
reopen if ever happens again
