### ISSUE TITLE
Speed is showing wrong speed

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#61]
Like in the title. The speed is showing me 2.3 GH/s. My GPU can't even come up to this. And it's always this speed.

**Comment by s77rt** [comment]
i'm unable to replicate the issue, can you please double check?
also try run those two commands from terminal:
`./hashcat.bin -m0 -a3 example0.hash ?a?a?a?a?a`
`./hashcat.bin -m0 -a3 example0.hash ?a?a?a?a?a --status-json`

**Comment by s77rt** [comment]
just did a check, not sure what i was looking for, just came to read your output again and everything seems fine?
3500 MH/s is 3.5 GH/s
and you are getting 2.3 GH/s which is expected (speed varies on your task, but overall seems okay
or did i miss something?

**Comment by foordeluxe** [comment]
Looks like everything is working like it should.
