### ISSUE TITLE
Info and Benchmark from old tool

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#62]
I wonder if these could be added again. To check the speed against a hash algorithm or info to showing if hashcat works like it should. I used these before to check that everything works like it should. And also to check my speed.

**Comment by s77rt** [comment]
Added in [v1.0.0](https://github.com/s77rt/hashcat.launcher/releases/tag/v1.0.0)

**Comment by foordeluxe** [comment]
Thanks.
