### ISSUE TITLE
A way to copy information from terminal

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#65]
I have seen copy in other windows. But not in terminal. Would help me or maybe many others to show errors or such from terminal.

**Comment by s77rt** [comment]
currently the copy button is only available for one text item
while the terminal is a collection of text items.

however you can still copy the text manually, select the text then press `CTRL + C`

**Comment by foordeluxe** [comment]
Yes I know that you can copy the text with CTRL + C, but would be nice with a copy button.
