### ISSUE TITLE
symlinks not reading through all folders

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#68]
When adding symlinks the tool doesn't include folders inside the directory. So the fix for now is to use one folder for everything. Which is taking even more space when I have sorted around my rules and dictionaries.

**Comment by foordeluxe** [comment]
Looks like this works. It's something with the directory rules that got added that don't read through folders. I can't get the list of my other rules.

**Comment by s77rt** [comment]
I didn't understand the problem exactly
Can you provide an example to how to reproduce the problem?

**Comment by foordeluxe** [comment]
I'm sorry, everything works like it should, I didn't see the scroll at the right when searching for rules or wordlists. But it was there.
