### ISSUE TITLE
Tool closes on hashcat file selection (Linux)

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#7]
I'm trying to select the file for hashcat in Linux from your tool. But the tool only closes every time.

**Comment by foordeluxe** [comment]
This happen to everything. Adding dictionarys, select output, select input and such.

**Comment by s77rt** [comment]
Hi,
This my be related to gtk, try install 
`apt-get install libgtk2.0-dev libglib2.0-dev libgtksourceview2.0-dev`

**Comment by foordeluxe** [comment]
Tried both of the installations. Still the same issue.

**Comment by s77rt** [comment]
Hi,
Thanks for your feedback, now kindly follow those steps:

1. open the terminal  
2. cd to your hashcat.launcher bin `cd /path/to/hashcat.launcher/`  
3. run hashcat.launcher from terminal `./hashcat.launcher`  
4. now, try again, and if the issue happen again you should get an error message in the terminal
5. paste it here

**Comment by foordeluxe** [comment]
Here is the result. https://pastebin.com/bB66vyg5

**Comment by Banthex** [comment]
Same problem here. https://pastebin.com/76saJNe1

**Comment by s77rt** [comment]
not quite sure as i didn't have the time to test this, we all what it seems it's a gtk issue.
( will update you soon )

**Comment by Jaja51** [comment]
Ok, so what's the fix? Thanks.

**Comment by s77rt** [comment]
a temporarily solution is to try and build hashcat.launcher from source
the gtk issues seems to be host related.
will be replaced by the native fyne file selector in the next version

**Comment by Jaja51** [comment]
Thanks for your response. I'm not familiar with go. I'm using 'go run main.go' to start the app.

**Comment by s77rt** [comment]
try this quick hack,
in go.mod file change:
`github.com/sqweek/dialog v0.0.0-20200601143742-43ea34326190` 
to
`github.com/sqweek/dialog v0.0.0-20200911184034-8a3d98e8211d`
then try again

**Comment by Jaja51** [comment]
Unfortunately, same problem:

`jean@linux:~/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher> go run main.go
go: finding github.com/sqweek/dialog v0.0.0-20200911184034-8a3d98e8211d
go: downloading github.com/sqweek/dialog v0.0.0-20200911184034-8a3d98e8211d
go: extracting github.com/sqweek/dialog v0.0.0-20200911184034-8a3d98e8211d
Welcome to hashcat.launcher v0.3.0
can't execute subprocess: fork/exec /home/jean/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher/hashcat.bin: no such file or directory
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fd62d859e40]

runtime stack:
runtime.throw(0xa27ba6, 0x2a)
        /usr/lib64/go/1.12/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /usr/lib64/go/1.12/src/runtime/signal_unix.go:374 +0x4a9

goroutine 36 [syscall]:
runtime.cgocall(0x8b08a0, 0xc00006dc58, 0x0)
        /usr/lib64/go/1.12/src/runtime/cgocall.go:128 +0x5b fp=0xc00006dc28 sp=0xc00006dbf0 pc=0x42ba6b
github.com/sqweek/dialog._Cfunc_gtk_dialog_run(0x7fd5d0006390, 0x7fd500000000)
        _cgo_gotypes.go:229 +0x49 fp=0xc00006dc58 sp=0xc00006dc28 pc=0x86aed9
github.com/sqweek/dialog.chooseFile.func11(0x7fd5d0006390, 0x7fd5d00054c0)
        /home/jean/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:93 +0x56 fp=0xc00006dc90 sp=0xc00006dc58 pc=0x86c356
github.com/sqweek/dialog.chooseFile(0xa0f2d1, 0x9, 0xa0ad7b, 0x4, 0x0, 0xc00006de58, 0x0, 0x0, 0x0, 0x0)
        /home/jean/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:93 +0x37c fp=0xc00006ddb8 sp=0xc00006dc90 pc=0x86b97c
github.com/sqweek/dialog.(*FileBuilder).load(...)
        /home/jean/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:55
github.com/sqweek/dialog.(*FileBuilder).Load(...)
        /home/jean/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs.go:112
github.com/s77rt/hashcat%2elauncher.optionsScreen.func1(0xa0f196, 0x9)
        /home/jean/Downloads/hashcat.launcher-0.3.0/optionsScreen.go:12 +0x227 fp=0xc00006dea0 sp=0xc00006ddb8 pc=0x8aaaf7
fyne.io/fyne/widget.(*Select).updateSelected(0xc00035a000, 0xa0f196, 0x9)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/select.go:246 +0x6a fp=0xc00006dec0 sp=0xc00006dea0 pc=0x7ca8ea
fyne.io/fyne/widget.(*Select).SetSelected(0xc00035a000, 0xa0f196, 0x9)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/select.go:237 +0xc6 fp=0xc00006df08 sp=0xc00006dec0 pc=0x7ca856
fyne.io/fyne/widget.(*Select).optionTapped(...)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/select.go:147
fyne.io/fyne/widget.(*Select).Tapped.func2()
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/select.go:166 +0x42 fp=0xc00006df38 sp=0xc00006df08 pc=0x7d1312
fyne.io/fyne/widget.(*menuItem).Tapped(0xc00014d1f0, 0xc0005121c0)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/widget/menu_item.go:135 +0x8d fp=0xc00006df58 sp=0xc00006df38 pc=0x7c431d
fyne.io/fyne/internal/driver/glfw.(*window).mouseClicked.func6()
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/window.go:695 +0x66 fp=0xc00006df98 sp=0xc00006df58 pc=0x7f5096
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc00033c000)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/window.go:1102 +0x7a fp=0xc00006dfd8 sp=0xc00006df98 pc=0x7f2aba
runtime.goexit()
        /usr/lib64/go/1.12/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00006dfe0 sp=0xc00006dfd8 pc=0x481421
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/window.go:1126 +0x103

goroutine 1 [select, locked to thread]:
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc0000a8410)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/loop.go:90 +0x197
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc0000a8410)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/driver.go:71 +0x37
main.main()
        /home/jean/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher/main.go:26 +0x1bb

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib64/go/1.12/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib64/go/1.12/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib64/go/1.12/src/os/signal/signal_unix.go:29 +0x41

goroutine 6 [sleep]:
runtime.goparkunlock(...)
        /usr/lib64/go/1.12/src/runtime/proc.go:307
time.Sleep(0x22ecb25c00)
        /usr/lib64/go/1.12/src/runtime/time.go:105 +0x159
fyne.io/fyne/internal/painter.svgCacheJanitor.func1()
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/painter/svg_cache.go:51 +0x116
sync.(*Once).Do(0x13c6438, 0xc000028490)
        /usr/lib64/go/1.12/src/sync/once.go:44 +0xb3
created by fyne.io/fyne/internal/painter.svgCacheJanitor
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/painter/svg_cache.go:49 +0x9b

goroutine 7 [chan receive]:
fyne.io/fyne/app.newAppWithDriver.func1(0xc000032360, 0xc0000367e0)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/app/app.go:113 +0x3d
created by fyne.io/fyne/app.newAppWithDriver
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/app/app.go:111 +0x184

goroutine 8 [syscall]:
syscall.Syscall6(0xe8, 0xe, 0xc000311d14, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib64/go/1.12/src/syscall/asm_linux_amd64.s:44 +0x5
golang.org/x/sys/unix.EpollWait(0xe, 0xc000311d14, 0x7, 0x7, 0xffffffffffffffff, 0xc000311d10, 0x0, 0xc000001c80)
        /home/jean/go/pkg/mod/golang.org/x/sys@v0.0.0-20200327173247-9dae0f8f5775/unix/zsyscall_linux_amd64.go:76 +0x72
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc000025200, 0xa34c00, 0xc000025200, 0x0)
        /home/jean/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify_poller.go:86 +0x91
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0000a8460)
        /home/jean/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify.go:192 +0x18a
created by github.com/fsnotify/fsnotify.NewWatcher
        /home/jean/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify.go:59 +0x1a8

goroutine 9 [chan receive]:
fyne.io/fyne/app.watchFile.func1(0xc0000a8460, 0xc00002a3f0, 0x25, 0xc000021730, 0xc000021740)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/app/settings_desktop.go:42 +0x58
created by fyne.io/fyne/app.watchFile
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/app/settings_desktop.go:41 +0xe7

goroutine 11 [chan receive]:
github.com/s77rt/hashcat%2elauncher.(*hcl_gui_monitor).Init.func1(0xc0000a84b0, 0xc0000ec768)
        /home/jean/Downloads/hashcat.launcher-0.3.0/monitor.go:27 +0x31
created by github.com/s77rt/hashcat%2elauncher.(*hcl_gui_monitor).Init
        /home/jean/Downloads/hashcat.launcher-0.3.0/monitor.go:24 +0x60

goroutine 35 [select, locked to thread]:
fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc0000a8410, 0xc000334000, 0xc0002ec050)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/loop.go:186 +0x10e
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/loop.go:182 +0xbd

goroutine 37 [chan receive]:
fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc000334060, 0xc000340000)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/canvas.go:506 +0x47
created by fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/driver/glfw/canvas.go:504 +0xa6

goroutine 40 [chan receive]:
main.main.func1(0xc00032d0e0, 0xc0000ec580)
        /home/jean/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher/main.go:21 +0x34
created by main.main
        /home/jean/Downloads/hashcat.launcher-0.3.0/cmd/hashcat.launcher/main.go:20 +0x193

goroutine 20 [chan receive]:
fyne.io/fyne/internal/painter.SvgCacheMonitorTheme.func1(0xc000032600)
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/painter/svg_cache.go:103 +0x34
created by fyne.io/fyne/internal/painter.SvgCacheMonitorTheme
        /home/jean/go/pkg/mod/fyne.io/fyne@v1.3.3/internal/painter/svg_cache.go:101 +0x9c
exit status 2
`

**Comment by s77rt** [comment]
hold on, i will make a fix for that and get rid of the whole dialog external package

**Comment by Jaja51** [comment]
> hold on, i will make a fix for that and get rid of the whole dialog external package

Alright, thank you very much :+1:

**Comment by s77rt** [comment]
v0.3.1 has been released
kindly try it (go build && ./hashcat.launcher)

(binaries will be available in the next hours)

**Comment by Jaja51** [comment]
> v0.3.1 has been released
> kindly try it (go build && ./hashcat.launcher)
> 
> (binaries will be available in the next hours)

Working perfectly now. Great job ! Thank you for your quick response Abdelhafidh

**Comment by s77rt** [comment]
binaries are available now. (v0.3.1: https://github.com/s77rt/hashcat.launcher/releases/tag/v0.3.1)
closing this issue now (finally :D)
