### ISSUE TITLE
Maybe options to change session id

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#72]
I remember the old way of session ids. Like #323 or such. And you could reset it. Somehow the old way was easier to remember which session that it was. Now it's text and I don't remember the sessions. 

Maybe an option to switch between old and new session way?

**Comment by s77rt** [comment]
tasks ids/sessions names has been changed to `Task #ID`
test with latest commit

**Comment by foordeluxe** [comment]
Did you add so you can reset the ids?

**Comment by s77rt** [comment]
Yes, it can be done from Settings

**Comment by foordeluxe** [comment]
Thanks. This is now solved.
