### ISSUE TITLE
When rescan in the tool it wont stop rescan

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#73]
As the tittle. It just keeps loading. The reason I want to rescan is that the automatic tool didn't detect my new rule I added.

**Comment by foordeluxe** [comment]
The whole tool froze when I did  this.

**Comment by s77rt** [comment]
On what version?
Did you have any sym links? Perhaps there was a cyclic import

**Comment by s77rt** [comment]
any chance you were saving to any of hashcat.launcher folders (hashcat/hashes, hashcat/rules, etc...)
or did you enable the option to remove found hashes? (in Advanced Options -> General)

**Comment by s77rt** [comment]
still checking
did you add the rules to /rules directory directly? or under another subfolder /rules/folder/
and how many rules did you add?

**Comment by s77rt** [comment]
i have made some changes to the file watcher, please try with the latest commit

**Comment by s77rt** [comment]
LIMITS
- File watcher does not watch folders recursively
- File watcher does not follow symlinks

**Comment by foordeluxe** [comment]
Sorry for a really old answer. Yes I select remove found hashes from hashfile. 
I saved the rules in the directory in hashcat folder.
I have around 100 rules.

**Comment by s77rt** [comment]
thanks for the feedback, i have made some changes, please try again

**Comment by foordeluxe** [comment]
I just downloaded the newest dev build. I'm not maybe going to add a new rule today.

**Comment by s77rt** [comment]
Alright, closing this for now
reopen if you face the issue again
