### ISSUE TITLE
Skipping a dict attack that only have 1 wordlist, will become grey

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#76]
Like in the title. No idea why I clicked on next when only having 1 wordlist in the dictionary attack. But the thing is, it's now a grey dot in the finished list and also have a skip title.

**Comment by s77rt** [comment]
Hi,
i don't see the problem? that's the expected behaviour
other than the dot is not really that grey, it's a little brighter than idle tasks dot
