### ISSUE TITLE
Possible to add tooltips?

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#8]
I wonder if it's possible to add tooltip to the "Guess Base" and "Guess Mod". So I can see which wordlist or which rule I use.
This isn't really needed, but easier to see the lists if you hover over with your mouse.

**Comment by s77rt** [comment]
If i understood you correctly, you want to see the list of the guesses so you know where you are and what's left, is that it?

**Comment by foordeluxe** [comment]
This can already been seen now. No need for tooltips.
