### ISSUE TITLE
Update ETA to show hour, min, seconds

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#80]
Like in the old tool it show like 2 min, 3 seconds. In this new tool it show just 3 minutes ago/left or a minute ago/left. Would be nice to show everything, like 3min, 2 sec or 2 hrs, 3 min, 1 sec

Example, this show only in a hour, which wouldn't tell me much:
![image](https://i.ibb.co/nfjHpVx/eta.png)

**Comment by s77rt** [comment]
I think the current behaviour is okay, and you can get the exact time by hovering the eta

**Comment by foordeluxe** [comment]
I know. I found out this when playing around in the client. I will close this now.
