### ISSUE TITLE
Autoloader is not automatic loading rules

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#82]
Like in the title. When adding rules in a symlink folder or in the folder rules. The Automatic method doesn't update the rules. I need to refresh every time I add a new rule. I don't know if this was only for dictionaries.

**Comment by s77rt** [comment]
adding rules to the rules directory itself trigger the auto load and load new rules, however adding new rules to a symlink folder or to a folder inside the rules folder does not and you will have to click on reload manually in this case.

see [LIMITS](https://github.com/s77rt/hashcat.launcher/blob/8e26d2a9d44eb1124f6e1460f603d6a418ec637b/LIMITS#L1-L2)
- File watcher does not watch folders recursively
- File watcher does not follow symlinks
