### ISSUE TITLE
Using around 10-12GB wordlist with big rules finished after 5 minutes

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#83]
I have tried to use a wordlist that is 10-12GB. The tool run and then show me it's only a second left, then around 5 minutes later everything is finished. I tested different rules and big ones too. Same time, 5 minutes. Maybe this is not the tools fault. Maybe an hashcat issue?

**Comment by s77rt** [comment]
the eta and the progress shown are for the current queue only and not for the whole task, that's by design on how hashcat works
