### ISSUE TITLE
Queue is not taking the first task added

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#84]
When adding new tasks they stay in queue before they run after current task. Now when the in progress task is finished. Instead of selecting Task 26, it select Task 28. I don't know if it should be like this.

**Comment by s77rt** [comment]
queued tasks are started automatically based only on their priorities
perhaps we should make it also based on the creation order

**Comment by foordeluxe** [comment]
Would be nice if it could go after creation order.

**Comment by s77rt** [comment]
Fixed.
New added tasks will be started in order sorted by priority then by creation time.

Please note this does not apply to restored tasks, as restored tasks does not contain info about the creation time so their execution order is not guaranteed. However restored tasks will always execute before new tasks (if they have same priority).

**Example:**
Tasks list: (assuming all tasks have the same priority)
Task #&#8203;7 (restored)
Task #&#8203;19 (restored)
Task #&#8203;20 (restored)
Task #&#8203;21 (new)
Task #&#8203;22 (new)
Task #&#8203;23 (new)
Task #&#8203;24 (new)

The order:
Task #&#8203;7, Task #&#8203;19 or Task #&#8203;20
Task #&#8203;7, Task #&#8203;19 or Task #&#8203;20
Task #&#8203;7, Task #&#8203;19 or Task #&#8203;20
Task #&#8203;21
Task #&#8203;22
Task #&#8203;23
Task #&#8203;24
