### ISSUE TITLE
A better way to delete task lists

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#85]
I know you can select on finished tasks and idle task, then go up far in the right corner to delete them. This is just making it more annoying to move the cursor to the right corner. Maybe change it when you rightclick on the list, you can then click on delete there?

**Comment by foordeluxe** [comment]
Or even more simplify, select and press DEL.

**Comment by s77rt** [comment]
I think it's better to keep it that way.
Simplifying the delete function may raise more problems than it solve, for one, you don't want to accidentally remove a task.
