### ISSUE TITLE
--session name is missing quotes because of space char

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#87]
When saving the command line, the -session name have space between the name. Quotes should be around the name because it's space in it. As example from command line:

Right now:  
```--session=Task #348```  

Should be:  
```--session="Task #348"```

**Comment by s77rt** [comment]
not to confuse with the removed label. this issue is valid.

**Comment by s77rt** [comment]
Fixed.
However the output is slightly different but still valid.
Before:
`--session=Task #348`
After:
`"--session=Task #348"`
