### ISSUE TITLE
panic: fork/exec : no such file or directory

### ISSUE THREAD

**Issue by s00x3r** [s77rt/hashcat.launcher#88]
./hashcat.launcher
panic: fork/exec : no such file or directory

goroutine 1 [running]:
main.main()
        /home/abdelhafidh/PROJECTS/hashcat.launcher/cmd/hashcat.launcher/main.go:24 +0x350

**Comment by s77rt** [comment]
Can you please provide steps to reproduce?

**Comment by s00x3r** [comment]
Downloaded hashcat.launcher_1.1.0_linux.zip, uncompressed and trying to launch ./hashcat.launcher

also compiled version ->
panic: fork/exec : no such file or directory

goroutine 1 [running]:
main.main()
        /tmp/hashcat.launcher/cmd/hashcat.launcher/main.go:24 +0x350

**Comment by s77rt** [comment]
what os?
do you have access to write to the tmp folder? `touch /tmp/test`

**Comment by s00x3r** [comment]
Ubuntu
yes

**Comment by s77rt** [comment]
i can't replicate the issue on my side, would it be possible to contact me on [telegram](https://t.me/s77rt) to look into your issue furthermore
