### ISSUE TITLE
Disable Archive from been added to the dictionary list.

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#9]
Since the last update you can even include archives inside the dictionary lists. When using load from folder it will import archives too.
I only know these formats, *.7z, *.tar *.zip I guess there is more of these.

**Comment by s77rt** [comment]
Hi,
I had to make it this way. restricting the files extensions could cause terrible problems.

Say you have a folder with the files:
file.txt file2.dict file3.text
And the filter is set to accept only (txt, dict, dic, lst) extensions, thus while you think you are adding the three files you are actually adding only file.txt and file2.dict, that's the issue. (we don't know what file extensions the user will be using)

So, It's better to add all the files (more files better than less) and leave it to the user to select a folder that contains text files only.
