### ISSUE TITLE
How to build hashcat.launcher on macOS and Apple silicon?

### ISSUE THREAD

**Issue by woOzZ2** [s77rt/hashcat.launcher#91]
The following way will fail to build the program 
```
git clone https://github.com/s77rt/hashcat.launcher.git
cd hashcat.launcher
make
```
How can I build hashcat.launcher for macOS?

**Comment by s77rt** [comment]
Can you please paste the error message you are getting?

**Comment by woOzZ2** [comment]
> 您能否粘贴您收到的错误消息？

`Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  280.79 KB  build/static/js/2.38191203.chunk.js
  64.31 KB   build/static/css/2.87bedb3e.chunk.css
  20.13 KB   build/static/js/main.12697635.chunk.js
  1.59 KB    build/static/js/3.a6160b3b.chunk.js
  1.15 KB    build/static/js/runtime-main.161aee54.js
  210 B      build/static/css/main.46826b3e.chunk.css

The project was built assuming it is hosted at /frontend/hashcat.launcher/build/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

Building hashcat.launcher for Linux
GOOS=linux GOARCH=amd64 go build -ldflags "-X 'github.com/s77rt/hashcat.launcher.Version="1.1.0"'" -o ./bin/linux/hashcat.launcher ./cmd/hashcat.launcher
# github.com/sqweek/dialog
../go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20211002065838-9a201b55ab91/dlgs.go:51:10: b.yesNo undefined (type *MsgBuilder has no field or method yesNo, but does have YesNo)
../go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20211002065838-9a201b55ab91/dlgs.go:56:3: b.info undefined (type *MsgBuilder has no field or method info, but does have Info)
../go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20211002065838-9a201b55ab91/dlgs.go:61:3: b.error undefined (type *MsgBuilder has no field or method error, but does have Error)
../go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20211002065838-9a201b55ab91/dlgs.go:112:10: b.load undefined (type *FileBuilder has no field or method load, but does have Load)
../go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20211002065838-9a201b55ab91/dlgs.go:121:10: b.save undefined (type *FileBuilder has no field or method save, but does have Save)
../go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20211002065838-9a201b55ab91/dlgs.go:139:10: b.browse undefined (type *DirectoryBuilder has no field or method browse, but does have Browse)
make: *** [build-linux] Error 2`

`$ go version
  go version go1.17.5 darwin/arm64`

I guess it didn't build projects for macOS, it was linux

**Comment by s77rt** [comment]
i just noticed that you are cross-compiling (that's the default behaviour stated in Makefile)
try compile only for mac:
`make build-frontend build-mac`

**Comment by s77rt** [comment]
cross-compilation is now easier to achieve.
(got ride of cgo dependencies caused by the file dialog handler https://github.com/s77rt/hashcat.launcher/commit/da8ed3522e580875b73d1317882c037423ff323a)

also next releases will contain all 3 os compiled binaries (Linux, Windows and macOS).
