### ISSUE TITLE
Using Chrome  edge  Translation into other national languages

### ISSUE THREAD

**Issue by LLH-l** [s77rt/hashcat.launcher#94]
Using Chrome does not automatically translate to other national languages
Using edge can automatically translate into other national languages, but some function translation pages cannot be displayed normally, and the content is empty

Hope to follow up on this issue, because it can support translation into many countries' languages

**Comment by s77rt** [comment]
Translation is not meant to be handled by the browser.
It's planned to add such functionality (#77)

**Comment by LLH-l** [comment]
good, very much looking forward to
