### ISSUE TITLE
Shortcuts for Windows doesn't work

### ISSUE THREAD

**Issue by foordeluxe** [s77rt/hashcat.launcher#95]
I was going to try out hashcat.launcher in Windows. I created shortcuts placed them in both \hashcat\dictionaries and \hashcat\rules. Refreshed the dictionary and rules. Then it found 1 dictionary which is the shortcut and 1 rule that is a shortcut too. I can see when selecting the dictionaries/rules that the shortcut is listed as a dictionary/rules. Also shortcut.lnk is there.

I have tested  symbolic links in Linux and everything works like it should.

**Comment by s77rt** [comment]
Hi,
Shortcuts are not supported.
Symlinks are.

You can create symlink in Windows too, so Windows is covered just as Linux.
To create a symlink use `mklink` command
Example:
```
cd C:\Users\Administrator\hashcat.launcher\hashcat\hashes
mklink hashCollectionA D:\Hashes\CollectionA
mklink hashCollectionB D:\Hashes\CollectionB
```

If you open hashcat.launcher you won't see hashCollectionA and hashCollectionB, instead you will see the hashes that are in their targets (D:\Hashes\CollectionA and D:\Hashes\CollectionB) just like you'd expect in Linux.
