### ISSUE TITLE
Please add a feature

### ISSUE THREAD

**Issue by LamerOnLine** [s77rt/hashcat.launcher#98]
A function that would show the loading of the dictionary as a percentage, before starting, an example in hashcat (screenshot).
https://www.dropbox.com/s/cj8v60xov6carvt/CWINDO~1.PNG?dl=0

**Comment by s77rt** [comment]
hashcat.launcher relied on the json output of hashcat
and currently hashcat does not provide such info.

Please open an issue(feature request) in [hashcat repo](https://github.com/hashcat/hashcat) to add "Dictionary cache building" info in the json output (terminal.c)

Closing this for now.
Reopen if needed (or if the feature got implemented in hashcat)
