### ISSUE TITLE
Please add Chinese language， please～💗

### ISSUE THREAD

**Issue by OKSHIJIAN** [s77rt/hashcat.launcher#99]
Please add Chinese language， please～💗
**Or can we have a video presentation？**
Translation software can't translate accurately

**Comment by s77rt** [comment]
Most added translations are not so accurate either
If you want to translate manually you'd have to translate this file https://github.com/s77rt/hashcat.launcher/blob/master/frontend/hashcat.launcher/public/locales/en/translation.json

**Comment by OKSHIJIAN** [comment]
我完成了中文翻译～

https://raw.githubusercontent.com/s77rt/hashcat.launcher/5ad7177100910e4c4d6349999156aabbf5f90e34/frontend/hashcat.launcher/public/locales/en/cn_translation.json

**Comment by s77rt** [comment]
do not misuse the edit function. create a new issue instead.
